#!/usr/bin/python3
def raise_exception():
    my_list = 1
    my_list2 = "e"

    result = my_list + my_list2

    return result
